apiVersion: v1
kind: Service
metadata:
  name: nodejs-cloudant-service
  labels:
    app: nodejs-cloudant
spec:
  type: NodePort
  selector:
    app: nodejs-cloudant
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000