# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
minReadySeconds: 5
revisionHistoryLimit: 1
image:
  repository: registry.mybluemix.net/replace-me-namespace/nodemicroservice
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret: bluemix-default-secret
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 3
service:
  name: Node
  type: NodePort
  externalPort: 3000
  internalPort: 3000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/config
    readOnly: true
  - name: secret-volume
    mountPath: /usr/src/app/secretConfig
    readOnly: true
configmap: |-
  {
        "cloudant": {
          "credentials": {
            "url": "none"
          },
          "database_name": "my_sample_db"
        },
        "log4js": {
          "appenders": {
            "out": {
              "type": "console",
              "layout": {
                "type": "coloured"
              }
            }
          },
          "categories": {
            "default": {
              "appenders": ["out"],
              "level": "debug"
            }
          }
        }
      }